apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: rparitosh/product-service:LATEST
        imagePullPolicy: Always
        ports:
          - containerPort: 9011
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: mysql_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: mysql_password
---

apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 9011
    targetPort: 9011
  type: NodePort

          
    
    

