server:
  port: 9011

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://mysql-service/eshop-product?useSSL=false
    username: $DB_USERNAME
    password: $DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true