server:
  port: 9011

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://paritosh-linux:3306/eshop-product
    username: root
    password: Marquis@1980
  jpa:
    hibernate:
      ddl-auto=update: update

